apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: channel-openshift-gitops
  namespace: acm-ocpgitops
  annotations:
    apps.open-cluster-management.io/reconcile-rate: high
spec:
  type: Git
  pathname: https://github.com/christianmarangoni/ocp-gitops.git
##  secretRef: reference for secret for channel
##    name:
