apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: channel-openshift-gitops
  namespace: openshift-gitops
spec:
  type: Git
  pathname: https://github.com/christianmarangoni/ocp-gitops.git
