apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: pr-openshift-gitops
  namespace: openshift-gitops
spec:
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
  clusterSelector:
    matchLabels:
      local-cluster: "true"
