apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: openshift-gitops-placementrule
  namespace: openshift-gitops
  labels:
    app: openshift-gitops
spec:
  clusterConditions:
    - type: "ManagedClusterConditionAvailable"
      status: "True"
  clusterSelector:
    matchExpressions:
    - key: role
      operator: In
      values:
      - active
      - bc
    matchLabels: {}
  clusterReplicas: 1