apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: pr-openshift-gitops
  namespace: acm-ocpgitops-prod
  labels:
    app: penshift-gitops
spec:
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
  clusterSelector:
    matchLabels:
      role: "bc"