apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: sub-openshift-gitops-prod
  namespace: acm-ocpgitops-prod
  labels:
    app: openshift-gitops
  annotations:
    apps.open-cluster-management.io/git-branch: structure
    apps.open-cluster-management.io/git-current-commit: 
    apps.open-cluster-management.io/git-path: config/gitops-operator
    apps.open-cluster-management.io/reconcile-option: replace
spec:
  channel: acm-ocpgitops/channel-openshift-gitops
  placement:
    placementRef:
      kind: PlacementRule
      name: pr-openshift-gitops