apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: sub-openshift-gitops-prod
  namespace: acm-ocpgitops
  labels:
    app: openshift-gitops
    pr: pr-openshift-gitops
  annotations:
    apps.open-cluster-management.io/github-path:  
    apps.open-cluster-management.io/git-branch: testing.gitops
    apps.open-cluster-management.io/git-current-commit: 
    apps.open-cluster-management.io/git-path: ocp-gitops
    apps.open-cluster-management.io/reconcile-option: replace
spec:
  channel: acm-ocpgitops/channel-openshift-gitops
  sourceNamespace:
  source:
  packageFilter:
    version:
    labelSelector:
      matchLabels:
        package:
        component:
    annotations:
  packageOverrides:
  - packageName:
    packageAlias:
    - path:
      value:
  placement:
    clusterSelector:
    placementRef:
      kind: PlacementRule
      name: pr-openshift-gitops
  overrides:
    clusterName:
    clusterOverrides:
      path:
      value:


