
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: openshift-gitops
  namespace: acm-ocpgitops
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - openshift-gitops
    matchLabels:
      key: value
